//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mmfm.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mmfm.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selecting  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Selecting {
            get {
                return ResourceManager.GetString("File_Selecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified at       に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Folders_ModifiedAt {
            get {
                return ResourceManager.GetString("Folders_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Folders_Name {
            get {
                return ResourceManager.GetString("Folders_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Cancel {
            get {
                return ResourceManager.GetString("MessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Confirm {
            get {
                return ResourceManager.GetString("MessageBox_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_No {
            get {
                return ResourceManager.GetString("MessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Documents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Pictures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyPictures {
            get {
                return ResourceManager.GetString("MyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quick Access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Navigation_QuickAccess {
            get {
                return ResourceManager.GetString("Navigation_QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you for using mmfm.&lt;LineBreak/&gt;If you would like to continue to use, please purchase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Store_ExpiredContent {
            get {
                return ResourceManager.GetString("Store_ExpiredContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trial period has been expired. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Store_ExpiredTitle {
            get {
                return ResourceManager.GetString("Store_ExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trial period will end in a {0} days. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Store_NotExipredTitle {
            get {
                return ResourceManager.GetString("Store_NotExipredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you were touched, please puchase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Store_NotExpiredContent {
            get {
                return ResourceManager.GetString("Store_NotExpiredContent", resourceCulture);
            }
        }
    }
}
